Repository amnezziaa/HenriBot, pull requests merged in 2023-02, with the labels that each got.

#1 feat(bot): setup google sheet api connection
  .gitignore
  commands/beloved.js
  commands/dailyChallenge.js
  example.env
  package-lock.json
  package.json
  utils/googleAuthorize.js
  utils/googleCredentialsManager.js
Labels: enhancement

#5 feat(bot): Make dailyChallenge command alter the google sheet
  commands/beloved.js
  commands/dailyChallenge.js
  example.env
  utils/dateFormatter.js
Labels: enhancement

#6 doc(readme): add setup, doc and more to readme
  readme.md
Labels: documentation, enhancement

#7 feat(embeds): display sheet update outcome
  commands/dailyChallenge.js
Labels: enhancement

#9 feat(dailyChallenge): better dates display
  commands/dailyChallenge.js
  readme.md
  utils/dateFormatter.js
  utils/googleCredentialsManager.js
Labels: enhancement

#12 typo(readme)
  readme.md
Labels: documentation

#15 feat(commands): add moneyspent command
  commands/moneySpent.js
  utils/google/getFailedChallenges.js
Labels: enhancement

#16 fix(dailyChallenge): wrong var name
  commands/dailyChallenge.js
Labels: bug
